<?php

require_once dirname(__FILE__) . '/dic.helper.inc';

/**
 * Retrieve the container
 *
 * @return \Symfony\Component\DependencyInjection\ContainerInterface
 */
function drupal_dic() {
  return _dic_get_helper()->getContainer();
}

/**
 * Implements @see hook_flush_caches().
 */
function dic_flush_caches() {
  _dic_get_helper()->flushCaches();

  return array();
}

/**
 * Implements @see hook_modules_installed().
 */
function dic_modules_installed(array $modules) {
  dic_flush_caches();

  // refresh bundle info cache
  _dic_get_bundle_info(false);
}

/**
 * Implements @see hook_modules_installed().
 */
function dic_modules_uninstalled(array $modules) {
  dic_modules_installed($modules);
}

/**
 * Implements @see hook_modules_enabled().
 */
function dic_modules_enabled(array $modules) {
  dic_modules_installed($modules);
}

/**
 * Implements @see hook_modules_disabled().
 */
function dic_modules_disabled($modules) {
  dic_modules_installed($modules);
}

/**
 * Implementation of @see hook_menu()
 */
function dic_menu() {
  $items = array();

  $items['admin/config/development/dic'] = array(
    'title' => 'Dependency Injection',
    'description' => "Configure Dependency Injection settings.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dic_admin_settings_form'),
    'access arguments' => array('administer dic'),
    'weight' => 10,
    'file' => 'dic.admin.inc',
  );

  return $items;
}

/**
 * Implementation of @see hook_dic_bundle_info()
 */
function dic_dic_bundle_info() {
  return array('bundles' => array("\\Drupal\\Dic\\Bundle\\DicBundle\\DicBundle"));
}
